basePath: /
definitions:
  valueobjects.Credentials:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@swagger.io
    name: Soporte
    url: http://www.swagger.io/support
  description: API para la gestión de autenticación, usuarios y productos
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Hexagonal DDD Golang Gin API
  version: "1.0"
paths:
  /api/login:
    post:
      consumes:
      - application/json
      description: Autentica a un usuario y devuelve un token JWT
      parameters:
      - description: Credenciales
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/valueobjects.Credentials'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Iniciar sesión
      tags:
      - Auth
swagger: "2.0"
